---
title: Support systems
---

A number of USC's schools provide support for students who need help with scholarly writing.  Check with your advisor or program staff to find out more.  Students whose primary language is not English should check with the <a href="http://dornsife.usc.edu/ali">American Language Institute</a>, which sponsors courses and workshops specifically for international graduate students. If an officially declared emergency makes travel to campus infeasible, <a href="http://emergency.usc.edu">USC Emergency Information</a> will provide safety and other updates, including ways in which instruction will be continued by means of blackboard, teleconferencing, and other technology.

The <a href="https://dsp.usc.edu/">Office of Disability Services and Programs</a> (DSP) provides certification for students with disabilities and helps arrange the relevant accommodations. Any student requesting academic accommodations based on a disability is required to register with DSP each semester. A letter of verification for approved accommodations can be obtained from DSP. Please be sure the letter is delivered to me as early in the semester as possible. DSP is located in STU 301 and is open 8:30 a.m. – 5:00 p.m., Monday through Friday. The phone number for DSP is (213) 740-0776.

Additional support systems:

- Counseling and Mental Health - (213) 740-9355 – 24/7 on call
    - [studenthealth.usc.edu/counseling](studenthealth.usc.edu/counseling)
    - Free and confidential mental health treatment for students, including short-term psychotherapy, group counseling, stress fitness workshops, and crisis intervention. 

- National Suicide Prevention Lifeline - 1 (800) 273-8255 – 24/7 on call
    - [suicidepreventionlifeline.org](suicidepreventionlifeline.org)
    - Free and confidential emotional support to people in suicidal crisis or emotional distress 24 hours a day, 7 days a week.

- Relationship and Sexual Violence Prevention Services (RSVP) - (213) 740-9355(WELL), press “0” after hours – 24/7 on call
    - [studenthealth.usc.edu/sexual-assault](studenthealth.usc.edu/sexual-assault)
    - Free and confidential therapy services, workshops, and training for situations related to gender-based harm.

- Office of Equity and Diversity (OED) - (213) 740-5086 | Title IX – (213) 821-8298
    - [equity.usc.edu](equity.usc.edu), [titleix.usc.edu](titleix.usc.edu)
    - Information about how to get help or help someone affected by harassment or discrimination, rights of protected classes, reporting options, and additional resources for students, faculty, staff, visitors, and applicants. 

- Reporting Incidents of Bias or Harassment - (213) 740-5086 or (213) 821-8298
    - [usc-advocate.symplicity.com/care_report](usc-advocate.symplicity.com/care_report)
    - Avenue to report incidents of bias, hate crimes, and microaggressions to the Office of Equity and Diversity |Title IX for appropriate investigation, supportive measures, and response.

- The Office of Disability Services and Programs - (213) 740-0776
    - [dsp.usc.edu](dsp.usc.edu)
    - Support and accommodations for students with disabilities. Services include assistance in providing readers/notetakers/interpreters, special accommodations for test taking needs, assistance with architectural barriers, assistive technology, and support for individual needs.

- USC Campus Support and Intervention - (213) 821-4710
    - [campussupport.usc.edu](campussupport.usc.edu)
    - Assists students and families in resolving complex personal, financial, and academic issues adversely affecting their success as a student.

- Diversity at USC - (213) 740-2101
    - [diversity.usc.edu](diversity.usc.edu)
    - Information on events, programs and training, the Provost’s Diversity and Inclusion Council, Diversity Liaisons for each academic school, chronology, participation, and various resources for students. 

- USC Emergency - UPC: (213) 740-4321, HSC: (323) 442-1000 – 24/7 on call 
    - [dps.usc.edu](dps.usc.edu), [emergency.usc.edu](emergency.usc.edu)
    - Emergency assistance and avenue to report a crime. Latest updates regarding safety, including ways in which instruction will be continued if an officially declared emergency makes travel to campus infeasible.

- USC Department of Public Safety - UPC: (213) 740-6000, HSC: (323) 442-120 – 24/7 on call 
    - [dps.usc.edu](dps.usc.edu)
    - Non-emergency assistance or information.

- Office of the Ombuds - (213) 821-9556 (UPC) / (323-442-0382 (HSC)
    - [ombuds.usc.edu](ombuds.usc.edu)
    - A safe and confidential place to share your USC-related issues with a University Ombuds who will work with you to explore options or paths to manage your concern.




